# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 630a8373c52378d52f0189155bf8ca1b2516114c7cc46b4d09368835a796a46b1ffabca17861a7cfeb3b64d506d30c2fe1a56529d18d9b1ec0b3cdefc3404dbb

test:
  secret_key_base: fe3748a04babc92a0521550f499149c7c5119be42567b71c150588b94ca3a18482b571ea33ae0fb284904d9af09dbb870fa628b497593b09b1b9c3f153243bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
